# Generated by Django 3.1.5 on 2021-01-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WcotaBaseNacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epi_week', models.BigIntegerField()),
                ('date', models.DateField()),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('ibgeid', models.BigIntegerField(db_column='ibgeID')),
                ('cod_regiaodesaude', models.FloatField(db_column='cod_RegiaoDeSaude')),
                ('name_regiaodesaude', models.TextField(db_column='name_RegiaoDeSaude')),
                ('newdeaths', models.BigIntegerField(db_column='newDeaths')),
                ('deaths', models.BigIntegerField()),
                ('newcases', models.BigIntegerField(db_column='newCases')),
                ('totalcases', models.BigIntegerField(db_column='totalCases')),
                ('deaths_per_100k_inhabitants', models.FloatField()),
                ('totalcases_per_100k_inhabitants', models.FloatField(db_column='totalCases_per_100k_inhabitants')),
                ('deaths_by_totalcases', models.FloatField(db_column='deaths_by_totalCases')),
                ('field_source', models.TextField(db_column='_source')),
                ('last_info_date', models.TextField()),
                ('insert_date', models.DateTimeField()),
            ],
        ),
    ]
