# Generated by Django 3.1.5 on 2021-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='cod_regiaodesaude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='deaths_by_totalcases',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='field_source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='ibgeid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='name_regiaodesaude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='newcases',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='newdeaths',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='totalcases',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='totalcases_per_100k_inhabitants',
            field=models.FloatField(),
        ),
    ]
