# Generated by Django 3.1.5 on 2021-01-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20210128_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wcotabasenacional',
            name='insert_date',
        ),
    ]
