# Generated by Django 3.1.5 on 2021-01-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_remove_wcotabasenacional_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='ibgeid',
            field=models.TextField(),
        ),
    ]
