# Generated by Django 3.1.5 on 2021-01-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210128_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='ibgeid',
            field=models.IntegerField(),
        ),
    ]
