# Generated by Django 3.1.5 on 2021-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0009_auto_20210128_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='ibgeid',
            field=models.FloatField(),
        ),
    ]
