# Generated by Django 3.1.5 on 2021-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0016_auto_20210128_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wcotabasenacional',
            name='epi_week',
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='deaths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='field_source',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='newcases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='newdeaths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='totalcases',
            field=models.IntegerField(),
        ),
    ]
