# Generated by Django 3.1.5 on 2021-01-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0018_auto_20210128_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='cod_regiaodesaude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='deaths_by_totalcases',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='deaths_per_100k_inhabitants',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='field_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='ibgeid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='last_info_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='name_regiaodesaude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='newcases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='newdeaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='totalcases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wcotabasenacional',
            name='totalcases_per_100k_inhabitants',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
